export const restaurants = [
  {
    id: 1,
    name: 'Jollof & Co.',
    description: 'Firewood flavour, generous portions, familiar comfort.',
    cuisineType: 'NIGERIAN',
    tags: ['Nigerian', 'Swallow', 'Grills'],
    deliveryTime: '25–35 min',
    deliveryFee: 500,
    rating: 4.6,
    image: '/assets/menu/jollof-chicken.png',
    isOpen: true,
  },
  {
    id: 2,
    name: "Mama T's Kitchen",
    description: 'Rich soups and proper home-style classics.',
    cuisineType: 'NIGERIAN',
    tags: ['Nigerian', 'Soups', 'Swallow'],
    deliveryTime: '30–40 min',
    deliveryFee: 400,
    rating: 4.5,
    image: '/assets/efo-riro.png',
    isOpen: true,
  },
  {
    id: 3,
    name: 'Suya Republic',
    description: 'Smoky skewers, bold yaji and late-night favourites.',
    cuisineType: 'FAST_FOOD',
    tags: ['Grills', 'Suya', 'Small chops'],
    deliveryTime: '20–30 min',
    deliveryFee: 600,
    rating: 4.7,
    image: '/assets/suya.png',
    isOpen: true,
  },
]

export const menuItems = [
  { id: 11, restaurantId: 1, name: 'Party Jollof & Chicken', description: 'Smoky party jollof with two pieces of flame-grilled chicken.', category: 'Popular', price: 4500, imageURL: '/assets/menu/jollof-chicken.png', isAvailable: true },
  { id: 12, restaurantId: 1, name: 'Nigerian Jollof Rice', description: 'Deeply seasoned tomato rice with peppers and our house spice blend.', category: 'Rice', price: 2800, imageURL: '/assets/menu/jollof-rice.webp', isAvailable: true },
  { id: 13, restaurantId: 1, name: 'Fried Rice & Chicken', description: 'Nigerian fried rice with vegetables, prawns and seasoned chicken.', category: 'Rice', price: 4200, imageURL: '/assets/menu/fried-rice.png', isAvailable: true },
  { id: 14, restaurantId: 1, name: 'Classic Beef Suya', description: 'Smoky beef skewers with yaji, onions, tomato and cucumber.', category: 'Grills', price: 3500, imageURL: '/assets/menu/beef-suya.webp', isAvailable: true },
  { id: 15, restaurantId: 1, name: 'Grilled Tilapia', description: 'Whole grilled tilapia finished with a bright Nigerian pepper sauce.', category: 'Grills', price: 8500, imageURL: '/assets/menu/grilled-tilapia.png', isAvailable: true },
  { id: 16, restaurantId: 1, name: 'Moi Moi', description: 'Steamed bean pudding—soft, savoury and perfect beside rice.', category: 'Sides', price: 1200, imageURL: '/assets/menu/moi-moi.png', isAvailable: true },
  { id: 17, restaurantId: 1, name: 'Goat Meat Pepper Soup', description: 'Aromatic pepper soup with tender goat meat and warming spices.', category: 'Soups', price: 4800, imageURL: '/assets/menu/pepper-soup.png', isAvailable: true },
  { id: 18, restaurantId: 1, name: 'Coconut Rice & Prawns', description: 'Fragrant coconut rice tossed with vegetables and juicy prawns.', category: 'Rice', price: 4600, imageURL: '/assets/menu/coconut-rice.webp', isAvailable: true },
  { id: 19, restaurantId: 1, name: 'Ofada Rice & Ayamase', description: 'Local Ofada rice served with bold green pepper ayamase and egg.', category: 'Rice', price: 5000, imageURL: '/assets/menu/ofada-rice-ayamase.webp', isAvailable: true },
  { id: 101, restaurantId: 1, name: 'Asaro Yam Porridge', description: 'Soft yam simmered in a rich palm-oil pepper sauce.', category: 'Mains', price: 3400, imageURL: '/assets/menu/asaro-yam-porridge.webp', isAvailable: true },
  { id: 102, restaurantId: 1, name: 'Nigerian Meat Pie', description: 'Golden pastry filled with seasoned minced beef and vegetables.', category: 'Pastries', price: 1600, imageURL: '/assets/menu/meat-pie.webp', isAvailable: true },
  { id: 103, restaurantId: 1, name: 'Abacha African Salad', description: 'Eastern Nigerian cassava salad with fish, vegetables and ugba.', category: 'Mains', price: 4200, imageURL: '/assets/menu/abacha.webp', isAvailable: true },
  { id: 21, restaurantId: 2, name: 'Efo Riro & Pounded Yam', description: 'Deeply seasoned vegetable stew with assorted meat.', category: 'Swallow', price: 5200, imageURL: '/assets/efo-riro.png', isAvailable: true },
  { id: 22, restaurantId: 2, name: 'Egusi Soup & Pounded Yam', description: 'Melon seed soup loaded with greens and assorted meat, served with pounded yam.', category: 'Swallow', price: 5400, imageURL: '/assets/menu/egusi-soup.webp', isAvailable: true },
  { id: 23, restaurantId: 2, name: 'Beans Porridge & Plantain', description: 'Creamy Nigerian beans porridge served with sweet fried plantain.', category: 'Mains', price: 3200, imageURL: '/assets/menu/beans-porridge.webp', isAvailable: true },
  { id: 24, restaurantId: 2, name: 'White Rice & Tomato Stew', description: 'Steamed rice with slow-cooked Nigerian tomato stew and tender beef.', category: 'Rice', price: 3800, imageURL: '/assets/menu/tomato-stew.webp', isAvailable: true },
  { id: 25, restaurantId: 2, name: 'Moi Moi', description: 'Steamed bean pudding with peppers and traditional spices.', category: 'Sides', price: 1200, imageURL: '/assets/menu/moi-moi.png', isAvailable: true },
  { id: 26, restaurantId: 2, name: 'Akara Breakfast', description: 'Crisp bean fritters served hot for a simple Lagos breakfast.', category: 'Breakfast', price: 1800, imageURL: '/assets/menu/akara.webp', isAvailable: true },
  { id: 27, restaurantId: 2, name: 'Ogbono Soup & Eba', description: 'Draw soup made with ground ogbono, greens and assorted meat.', category: 'Swallow', price: 5200, imageURL: '/assets/menu/ogbono-soup.webp', isAvailable: true },
  { id: 28, restaurantId: 2, name: 'Okra Soup & Pounded Yam', description: 'Fresh chopped okra cooked with fish and assorted meat.', category: 'Swallow', price: 5300, imageURL: '/assets/menu/okra-soup.webp', isAvailable: true },
  { id: 29, restaurantId: 2, name: 'Afang Soup & Fufu', description: 'A hearty Cross River vegetable soup with assorted meat.', category: 'Swallow', price: 5600, imageURL: '/assets/menu/afang-soup.webp', isAvailable: true },
  { id: 30, restaurantId: 2, name: 'Banga Soup & Starch', description: 'Palm fruit soup with traditional spices, fish and meat.', category: 'Swallow', price: 5700, imageURL: '/assets/menu/banga-soup.webp', isAvailable: true },
  { id: 201, restaurantId: 2, name: 'Pap & Akara', description: 'Creamy pap served with freshly fried bean cakes.', category: 'Breakfast', price: 2300, imageURL: '/assets/menu/pap-and-akara.webp', isAvailable: true },
  { id: 31, restaurantId: 3, name: 'Classic Beef Suya', description: 'Smoky beef skewers with onions, cabbage and yaji.', category: 'Grills', price: 3500, imageURL: '/assets/menu/beef-suya.webp', isAvailable: true },
  { id: 32, restaurantId: 3, name: 'Chicken Suya', description: 'Juicy grilled chicken coated in a bold house yaji blend.', category: 'Grills', price: 4000, imageURL: '/assets/menu/chicken-suya.webp', isAvailable: true },
  { id: 33, restaurantId: 3, name: 'Grilled Tilapia', description: 'Whole tilapia grilled over flame and finished with pepper sauce.', category: 'Grills', price: 8500, imageURL: '/assets/menu/grilled-tilapia.png', isAvailable: true },
  { id: 34, restaurantId: 3, name: 'Suya Party Box', description: 'A generous sharing box of beef suya, vegetables and extra spice.', category: 'Popular', price: 7500, imageURL: '/assets/suya.png', isAvailable: true },
  { id: 35, restaurantId: 3, name: 'Goat Meat Pepper Soup', description: 'Tender goat meat in a warming, aromatic pepper broth.', category: 'Soups', price: 4800, imageURL: '/assets/menu/pepper-soup.png', isAvailable: true },
  { id: 36, restaurantId: 3, name: 'Party Jollof & Suya', description: 'Smoky party jollof paired with freshly grilled beef suya.', category: 'Rice', price: 5200, imageURL: '/assets/menu/jollof-rice.webp', isAvailable: true },
  { id: 37, restaurantId: 3, name: 'Nkwobi', description: 'Tender cow foot tossed in a spicy palm-oil sauce.', category: 'Native Pots', price: 5200, imageURL: '/assets/menu/nkwobi.webp', isAvailable: true },
  { id: 38, restaurantId: 3, name: 'Isi Ewu', description: 'Traditional spiced goat head finished with onions and herbs.', category: 'Native Pots', price: 6500, imageURL: '/assets/menu/isi-ewu.webp', isAvailable: true },
  { id: 39, restaurantId: 3, name: 'Puff Puff', description: 'Soft, golden Nigerian dough bites served warm.', category: 'Small Chops', price: 1500, imageURL: '/assets/menu/puff-puff.webp', isAvailable: true },
  { id: 40, restaurantId: 3, name: 'Bole & Grilled Fish', description: 'Roasted plantain with grilled fish and fiery pepper sauce.', category: 'Grills', price: 6800, imageURL: '/assets/menu/bole-grilled-fish.webp', isAvailable: true },
  { id: 41, restaurantId: 3, name: 'Asun', description: 'Smoky grilled goat meat tossed with chopped peppers and onions.', category: 'Grills', price: 5000, imageURL: '/assets/menu/asun.webp', isAvailable: true },
]

export const ownerOrders = [
  { id: 5921, customer: 'Tosin A.', items: 2, total: 7500, status: 'PENDING', time: '10:24 AM', address: '12 Admiralty Way, Lekki Phase 1', payment: 'Cash on delivery' },
  { id: 5920, customer: 'Chinedu K.', items: 3, total: 12200, status: 'CONFIRMED', time: '10:18 AM', address: 'Ikoyi, Lagos', payment: 'Paystack' },
  { id: 5919, customer: 'Amaka O.', items: 1, total: 4000, status: 'PREPARING', time: '10:12 AM', address: 'Victoria Island, Lagos', payment: 'Paystack' },
  { id: 5918, customer: 'Bola S.', items: 4, total: 15500, status: 'PREPARING', time: '10:05 AM', address: 'Oniru, Lagos', payment: 'Cash on delivery' },
  { id: 5917, customer: 'Ibrahim M.', items: 2, total: 7000, status: 'READY_FOR_PICKUP', time: '9:58 AM', address: 'Lekki Phase 1, Lagos', payment: 'Paystack' },
  { id: 5916, customer: 'Adaobi E.', items: 1, total: 3500, status: 'CONFIRMED', time: '9:45 AM', address: 'Yaba, Lagos', payment: 'Paystack' },
]

export const categories = ['All', 'Nigerian', 'Breakfast', 'Swallow', 'Grills', 'Small chops', 'Healthy', 'Drinks']
